"""Add new student fields

Revision ID: 260a4ab0d8c3
Revises: 8d9b3075753d
Create Date: 2025-10-27 01:57:35.090436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '260a4ab0d8c3'
down_revision: Union[str, None] = '8d9b3075753d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('student_id', sa.String(length=50), nullable=True))
    op.add_column('students', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('students', sa.Column('parent_phone', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_students_student_id'), 'students', ['student_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_student_id'), table_name='students')
    op.drop_column('students', 'parent_phone')
    op.drop_column('students', 'date_of_birth')
    op.drop_column('students', 'student_id')
    # ### end Alembic commands ###
